"""add expense breakdown columns

Revision ID: aed006ffbb88
Revises: 001_account_system
Create Date: 2025-11-15 17:21:03.667594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'aed006ffbb88'
down_revision: Union[str, None] = '001_account_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we skip these:
    # op.alter_column('accounts', 'default_aspirations',
    #            existing_type=sqlite.JSON(),
    #            nullable=True)
    
    # Add expense breakdown columns with default values
    op.add_column('game_states', sa.Column('expense_housing', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_food', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_transport', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_utilities', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_subscriptions', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_insurance', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('expense_other', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('game_states', sa.Column('cached_next_narrative', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game_states', sa.Column('cached_next_options', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # SQLite doesn't support ALTER COLUMN, so we skip these:
    # op.alter_column('leaderboard', 'is_test_mode',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('player_profiles', 'is_test_mode',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we skip these:
    # op.alter_column('player_profiles', 'is_test_mode',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text("'0'"),
    #            existing_nullable=False)
    # op.alter_column('leaderboard', 'is_test_mode',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=sa.text("'0'"),
    #            existing_nullable=False)
    
    op.drop_column('game_states', 'cached_next_options')
    op.drop_column('game_states', 'cached_next_narrative')
    op.drop_column('game_states', 'expense_other')
    op.drop_column('game_states', 'expense_insurance')
    op.drop_column('game_states', 'expense_subscriptions')
    op.drop_column('game_states', 'expense_utilities')
    op.drop_column('game_states', 'expense_transport')
    op.drop_column('game_states', 'expense_food')
    op.drop_column('game_states', 'expense_housing')
    
    # SQLite doesn't support ALTER COLUMN, so we skip this:
    # op.alter_column('accounts', 'default_aspirations',
    #            existing_type=sqlite.JSON(),
    #            nullable=False)
    # ### end Alembic commands ###
